In [3]:
#[Petro Cognitive Lab](data/PCL.png)

<img src="../data/PCL.png" width="200" height="200">

# **Working on Files**

In [1]:
%pwd

'/home/sagemaker-user/data_exploration'

## Utility & Product files

In [2]:
import pandas as pd
import numpy as np
import os
from pathlib import Path
from IPython.display import display, HTML

In [3]:
!pip install openpyxl > /dev/null
!pip install xlrd

Collecting xlrd
  Using cached xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Using cached xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [4]:
han_u = pd.read_excel("../data/han/utility.xlsx", skiprows=2)
han_u.head()

,FQI91513\nSW\nSm3,FQI91512\nProcess Water\nSm3,FQI90025\nSN\nSm3,FQI88503\nPCW\nSm3,FQI91501\nIA\nNM3,FQI91502\nPA\nNM3,FQI91503\nN2\nNM3,FQI91504\nDSW\nSm3,FQI91507\nPW\nSm3,FQI91506\nNG\nNM3,FQI91508\nHPS\nTON,FQI91505\nCONDENSE\nSm3,FQI91509\nDMW\nSm3,FQI91510\nBFW\nSm3,-\nCW\nSm3,تاریخ
0,0,0.162,28.908,69.51,26538.989,25600.873,83494.946,710.193,0,530623.2,4373.524,6813.863,114.345,3010.805,570866.231,1399-01-01
1,0,0.384,64.04,257.017,25705.529,24715.538,78541.542,593.413,0,505403.628,4173.1,6557.989,109.076,2896.463,547366.495,1399-01-02
2,0,0.037,94.752,325.813,27011.942,25638.707,81321.383,547.826,0,543229.319,4427.988,6845.993,126.251,3055.477,571161.005,1399-01-03
3,0,0.002,114.81,460.313,27687.705,25948.415,76596.753,647.282,0,537326.367,4470.822,6938.854,120.808,3129.186,571243.001,1399-01-04
4,0,0.068,62.801,482.603,27850.721,25917.436,84247.025,772.217,0,535247.3,4406.786,6907.477,129.308,3103.997,571535.789,1399-01-05

In [5]:
han_p = pd.read_excel("../data/han/product.xlsx", skiprows=2)
han_p.head()

,مجموع,GC Mid-Cut,مخلوط زایلین,A92,A80,HTN,آروماتیک سنگین,LPG,برش پنتان,رافینیت,ترکیبات سنگین,ترکیبات سبک,پارازایلین,اورتوزایلین,بنزن,تاریخ
0,12861,-,0,-,-,0,142,261,259,2316,4389,2024,2132,95,1243,1399-01-01
1,12218,-,0,-,-,0,139,269,250,1969,4288,1966,2053,88,1196,1399-01-02
2,12813,-,0,-,-,0,141,278,258,2284,4382,2043,2170,103,1154,1399-01-03
3,12564,-,0,-,-,0,143,280,258,2341,3961,2034,2171,96,1280,1399-01-04
4,12490,-,0,-,-,0,145,258,256,2270,3917,2094,2192,95,1263,1399-01-05

In [6]:
xls = pd.ExcelFile("../data/petrochem/Total_Report20251115_015007.xls")
print(xls.sheet_names)

['WData', 'Sheet1', 'Sheet2', 'Sheet3']

In [37]:
total = pd.read_excel("../data/petrochem/Total_Report20251115_015007.xls", sheet_name='Sheet1')
total.head()

   Unnamed: 0  Unnamed: 1  ...  2025-11-14 23:59:00    Unnamed: 30
0         NaN         TAG  ...  1900-01-01 00:00:00  TOTAL 24 Hour
1         1.0  AI40003_PV  ...      4.4049072265625     104.761353
2         2.0  AI40004_PV  ...          7.529296875     185.772095
3         3.0  AI40005_PV  ...       6.177978515625     148.378906
4         4.0  FI40065_PV  ...       4076.583984375   91860.901367

[5 rows x 31 columns]

In [8]:
total['Unnamed: 1'].unique()

array(['TAG', 'AI40003_PV', 'AI40004_PV', ..., 'DI95008_PV', 'DI95013_PV',
       'DI95023_PV'], dtype=object)

In [9]:
total['Unnamed: 1'].nunique()

3106

In [10]:
'AI40003_PV' in total['Unnamed: 1'].values

True

In [64]:
total[total['Unnamed: 1'].str.contains('95008', na=False)]

      Unnamed: 0    Unnamed: 1  ... 2025-11-14 23:59:00    Unnamed: 30
3119        14.0   FIC95008_PV  ...        141216.59375  3370260.03125
3133        25.0  FQI95008_CPV  ...          2268551.75       54406436
3134        25.0  FQI95008_CPV  ...               141.5         3364.5
3802       147.0    DI95008_PV  ...   613.0479736328125   14728.289429

[4 rows x 31 columns]

In [75]:
total[total['Unnamed: 2'].str.contains('LPG', na=False)]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,2025-11-14 00:59:00,2025-11-14 01:59:00,2025-11-14 02:59:00,2025-11-14 03:59:00,...,2025-11-14 15:59:00,2025-11-14 16:59:00,2025-11-14 17:59:00,2025-11-14 18:59:00,2025-11-14 19:59:00,2025-11-14 20:59:00,2025-11-14 21:59:00,2025-11-14 22:59:00,2025-11-14 23:59:00,Unnamed: 30
1190,17.0,TI30076_PV,LPG TO TK-8104,DEGC,TK-8104,300,37.490966796875,37.649383544921875,37.64898681640625,37.39886474609375,...,37.760986328125,37.716278076171875,37.512786865234375,37.487945556640625,37.473388671875,37.416656494140625,37.5001220703125,37.529388427734375,37.6478271484375,903.863617
2891,12.0,FI80039_PV,LPG TO H-8002,NM3/H,H-8002,800,3514.922119140625,3592.284423828125,3653.904541015625,3610.32177734375,...,3529.462158203125,3568.4150390625,3564.338623046875,3548.561279296875,3565.16552734375,3626.445068359375,3598.243408203125,3558.271240234375,3503.322021484375,85589.807373
3008,122.0,FQI80039_CPV,LPG TO H-8002,NM3,H-8002,800,90947944,90951512,90955088,90958664,...,91001368,91004936,91008504,91012072,91015648,91019216,91022792,91026360,91029920,2183734600
3009,122.0,FQI80039_CPV,LPG TO H-8002,NM3,H-8002,800,3576,3568,3576,3576,...,3552,3568,3568,3568,3576,3568,3576,3568,3560,85552
3311,10.0,FQIC81520_CPV,LPG TO LA-8204,KG/H,LA-8204,8000,-,-,-,-,...,-,-,-,-,-,-,-,-,-,NaN
3312,10.0,FQIC81520_CPV,LPG TO LA-8204,KG/H,LA-8204,8000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3351,38.0,FQI81521_CPV,LPG TO PARS,TNE,P-8104A/B,8000,470645.84375,470670.75,470695.5625,470720.375,...,471016.3125,471041.15625,471066,471090.78125,471115.71875,471140.65625,471165.625,471190.625,471215.59375,11302328.25
3352,38.0,FQI81521_CPV,LPG TO PARS,TNE,P-8104A/B,8000,24.84375,24.90625,24.8125,24.8125,...,24.84375,24.84375,24.84375,24.78125,24.9375,24.9375,24.96875,25,24.96875,594.59375
3374,51.0,FQI81506_CPV,LPG TO B/L,KG,P-8112A/B,8000,32279.28515625,32283.861328125,32288.45703125,32293.025390625,...,32347.60546875,32352.201171875,32356.7890625,32361.36328125,32365.994140625,32370.6640625,32375.33203125,32380,32384.662109375,775962.373047
3375,51.0,FQI81506_CPV,LPG TO B/L,KG,P-8112A/B,8000,4.59375,4.576172,4.595703,4.568359,...,4.599609,4.595703,4.587891,4.574219,4.630859,4.669922,4.667969,4.667969,4.662109,109.970703
3448,123.0,PI82511_PV,LPG TO LA8204,BAR,LA-8204,8000,Null,Null,Null,Null,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,NaN
3454,129.0,TI82513_PV,LPG TO LA8204,DEGC,LA-8204,8000,Null,Null,Null,Null,...,Null,Null,Null,Null,Null,Null,Null,Null,Null,NaN
3468,143.0,FQI84001_CPV,LPG FROM P-8104A/B,TNE,P-8104A/B,8000,88526.875,88533.25,88539.640625,88546.015625,...,88623,88629.375,88635.7578125,88642.1328125,88648.5,88654.8671875,88661.265625,88667.640625,88674.0078125,2126411.460938
3469,143.0,FQI84001_CPV,LPG FROM P-8104A/B,TNE,P-8104A/B,8000,6.382812,6.375,6.390625,6.375,...,6.390625,6.375,6.382812,6.375,6.367188,6.367188,6.398438,6.375,6.367188,153.515625
3482,153.0,FIC84002_PV,LPG FROM E-8402,NM3/H,E-8402,8000,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3483,154.0,FIC84001_PV,LPG FROM P-8401A/B,Sm3/h,P-8401A/B,8000,11.945510864257812,12.005298614501953,12.018229484558105,12.014808654785156,...,12.031025886535645,11.955512046813965,12.029825210571289,11.974843978881836,11.985918998718262,12.008012771606445,12.034242630004883,11.977229118347168,11.999032020568848,288.588796
3766,111.0,DI30020_PV,LPG TO TK-8104,NaN,NaN,NaN,510.71749877929687,511.875,512.900634765625,512.36248779296875,...,520.151611328125,521.352294921875,522.72491455078125,522.81353759765625,522.126220703125,521.6534423828125,522.56219482421875,522.66082763671875,523.5540771484375,12449.479462
3791,136.0,DI81506_PV,LPG TO BL,NaN,NaN,NaN,533.5584716796875,533.44500732421875,533.664306640625,533.820556640625,...,534.47869873046875,535.91070556640625,536.7420654296875,537.06610107421875,537.505126953125,538.137451171875,538.58587646484375,539.0167236328125,539.0338134765625,12826.305115
3798,143.0,DI81520_PV,LPG TO LA-8204,NaN,NaN,NaN,527.2109375,527.1392822265625,527.24774169921875,527.346923828125,...,528.7073974609375,529.66595458984375,530.1942138671875,530.634521484375,531.0684814453125,531.49658203125,531.85498046875,532.35260009765625,532.5078125,12681.23407

In [7]:
from pathlib import Path
import pandas as pd
parquet_dir = Path("../data/parquet/by_equipment")
parquet_files = list(parquet_dir.rglob("*.parquet"))

print(f"Found {len(parquet_files)} parquet files")

Found 1090 parquet files

#### Extracting **Utility** Tags from by_equipment.parquet

OK(12): FQI91501, FQI91502, FQI91503, FQI91504, FQI91505, FQI91506, FQI91507, FQI91508, FQI91509, FQI91510, FQI91512, FQI91513  
**NOT OK(3)**: FQI86502, FQI8503, FQI90025

In [29]:
search_term = 'FI91513'
results = []

In [30]:
for file in parquet_files:
    df = pd.read_parquet(file)
    for col in df.select_dtypes(include='object').columns:
        mask = df[col].str.contains(search_term, na=False)
        if mask.any():
            matches = df[mask].copy()
            matches['source_file'] = file.name
            results.append(matches)

In [31]:
if results:
    all_matches = pd.concat(results, ignore_index=True)
    print(f"Found {len(all_matches)} matching rows")
    display(all_matches)
else:
    print("No matches found")

Found 35696 matching rows

                 Datetime         TAG  ...  SECTION             source_file
0     2021-05-01 01:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
1     2021-05-01 02:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
2     2021-05-01 03:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
3     2021-05-01 04:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
4     2021-05-01 05:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
...                   ...         ...  ...      ...                     ...
35691 2025-11-18 19:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35692 2025-11-18 20:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35693 2025-11-18 21:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35694 2025-11-18 22:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35695 2025-11-18 23:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet

[35696 rows x 8 columns]

In [32]:
all_matches

                 Datetime         TAG  ...  SECTION             source_file
0     2021-05-01 01:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
1     2021-05-01 02:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
2     2021-05-01 03:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
3     2021-05-01 04:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
4     2021-05-01 05:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
...                   ...         ...  ...      ...                     ...
35691 2025-11-18 19:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35692 2025-11-18 20:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35693 2025-11-18 21:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35694 2025-11-18 22:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet
35695 2025-11-18 23:00:00  FI91513_PV  ...   9000.0  UTILITY_U-9100.parquet

[35696 rows x 8 columns]

In [33]:
(all_matches['Value']>0).sum()

2182

In [34]:
total_rows = len(all_matches)
positive = (all_matches['Value'] > 0).sum()
print(f"Value>0: {positive}/{total_rows} ({100*positive/total_rows:.1f}%)")

Value>0: 2182/35696 (6.1%)

In [35]:
all_matches.to_parquet(f"../data/petrochem/{search_term}_u.parquet", index=False)

### **Cooling Water**:

OK: FI10203, FI20203, FI25205, FI40205, FI50205, FI60204, FI65204, FI70253

**NOT OK**: No matches found: FI30205(FRQ30205), FI80205(FRQ80205), FI84205(FRQ84205), FRQ95107, FQI97004, FRQ97204, FRQ30205,

In [5]:
from pathlib import Path
import pandas as pd
parquet_dir = Path("../data/parquet/by_equipment")
parquet_files = list(parquet_dir.rglob("*.parquet"))

print(f"Found {len(parquet_files)} parquet files")

Found 1090 parquet files

In [21]:
search_term = 'FI70253'
results = []

In [22]:
for file in parquet_files:
    df = pd.read_parquet(file)
    for col in df.select_dtypes(include='object').columns:
        mask = df[col].str.contains(search_term, na=False)
        if mask.any():
            matches = df[mask].copy()
            matches['source_file'] = file.name
            results.append(matches)

In [23]:
if results:
    all_matches = pd.concat(results, ignore_index=True)
    print(f"Found {len(all_matches)} matching rows")
    display(all_matches)
else:
    print("No matches found")

Found 35696 matching rows

,Datetime,TAG,Value,Desc.,Unit,Equipment,SECTION,source_file
0,2021-05-01 01:00:00,FI70253_PV,873.822632,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
1,2021-05-01 02:00:00,FI70253_PV,873.830811,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
2,2021-05-01 03:00:00,FI70253_PV,873.869019,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
3,2021-05-01 04:00:00,FI70253_PV,873.907043,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
4,2021-05-01 05:00:00,FI70253_PV,873.883911,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
...,...,...,...,...,...,...,...,...
35691,2025-11-18 19:00:00,FI70253_PV,1605.046265,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
35692,2025-11-18 20:00:00,FI70253_PV,1596.674316,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
35693,2025-11-18 21:00:00,FI70253_PV,1602.154175,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
35694,2025-11-18 22:00:00,FI70253_PV,1572.333984,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet
35695,2025-11-18 23:00:00,FI70253_PV,1512.986816,CWS FROM 9100,Sm3/h,UTILITY U-700,700.0,UTILITY_U-700.parquet

In [24]:
total_rows = len(all_matches)
positive = (all_matches['Value'] > 0).sum()
print(f"Value>0: {positive}/{total_rows} ({100*positive/total_rows:.1f}%)")

Value>0: 34902/35696 (97.8%)

In [25]:
all_matches.to_parquet(f"../data/petrochem/{search_term}_cw_u.parquet", index=False)

### sum of all cooling waters

## product files
OK: FIC10014(FQI10014), FIC20017, FIC20018, FIC25021, FIC30018, FI40039(FQI40039), FIC40045, FIC50011, FIC60020, FIC65004, FIC70053, FIC95008

**NOT OK**: FQI30020

In [1]:
import pandas as pd
from pathlib import Path
parquet_dir = Path("../data/parquet/by_equipment")
parquet_files = list(parquet_dir.rglob("*.parquet"))

print(f"Found {len(parquet_files)} parquet files")

Found 1090 parquet files

In [2]:
search_term = 'FI40039'
results = []

In [3]:
for file in parquet_files:
    df = pd.read_parquet(file)
    for col in df.select_dtypes(include='object').columns:
        mask = df[col].str.contains(search_term, na=False)
        if mask.any():
            matches = df[mask].copy()
            matches['source_file'] = file.name
            results.append(matches)

In [5]:
if results:
    all_matches = pd.concat(results, ignore_index=True)
    print(f"Found {len(all_matches)} matching rows")
    display(all_matches)
else:
    print("No matches found")

Found 35696 matching rows

,Datetime,TAG,Value,Desc.,Unit,Equipment,SECTION,source_file
0,2021-05-01 01:00:00,FI40039_PV,1673.277588,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
1,2021-05-01 02:00:00,FI40039_PV,0.000000,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
2,2021-05-01 03:00:00,FI40039_PV,0.000000,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
3,2021-05-01 04:00:00,FI40039_PV,661.154236,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
4,2021-05-01 05:00:00,FI40039_PV,0.000000,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
...,...,...,...,...,...,...,...,...
35691,2025-11-18 19:00:00,FI40039_PV,225512.078125,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
35692,2025-11-18 20:00:00,FI40039_PV,199399.593750,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
35693,2025-11-18 21:00:00,FI40039_PV,200614.609375,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
35694,2025-11-18 22:00:00,FI40039_PV,219199.031250,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet
35695,2025-11-18 23:00:00,FI40039_PV,232263.937500,MIXED XYLENES,KG/H,E-4012,400.0,E-4012.parquet

In [6]:
total_rows = len(all_matches)
positive = (all_matches['Value'] > 0).sum()
print(f"Value>0: {positive}/{total_rows} ({100*positive/total_rows:.1f}%)")

Value>0: 20051/35696 (56.2%)

In [7]:
all_matches.to_parquet(f"../data/petrochem/{search_term}_p.parquet", index=False)

### Table Summary

In [8]:
%pwd

'/home/sagemaker-user'

In [8]:
parquet_dir_up = Path("/home/sagemaker-user/data/petrochem")

In [9]:
u_files = list(parquet_dir_up.glob("*_u.parquet"))
p_files = list(parquet_dir_up.glob("*_p.parquet"))

In [10]:
def create_summary(files):
    rows = []
    for f in files:
        df = pd.read_parquet(f)
        row = {
            'TAG':df['TAG'].iloc[0] if 'TAG' in df.columns else f.stem,
            'Unit':df['Unit'].iloc[0] if 'Unit' in df.columns else None,
            'Equipment':df['Equipment'].iloc[0] if 'Equipment' in df.columns else None,
            'Desc.':df['Desc.'].iloc[0] if 'Desc.' in df.columns else None,
            '#Value>0':(df['Value']>0).sum() if 'Value' in df.columns else 0
        }
        rows.append(row)
    return pd.DataFrame(rows)

In [11]:
utility_table = create_summary(u_files)
product_table = create_summary(p_files)

In [12]:
print(f"Found {len(u_files)} utility files")
print(f"Found {len(p_files)} product files")

Found 20 utility files
Found 13 product files

In [13]:
from IPython.display import display, HTML

display(HTML("<h3>Utility Files</h3>"))
display(utility_table)

           TAG   Unit       Equipment                     Desc.  #Value>0
0   FI91501_PV  NM3/H  UTILITY U-9100           INSTRUMENT  AIR     34902
1   FI91502_PV  NM3/H  UTILITY U-9100                PLANT AIR      34814
2   FI91503_PV  NM3/H  UTILITY U-9100                  NITROGEN     34902
3   FI91504_PV  Sm3/h  UTILITY U-9100         DESALINATED WATER     34879
4   FI91505_PV  Sm3/h  UTILITY U-9100   LOW PRESSURE CONDENSATE     34902
5   FI91506_PV  NM3/H  UTILITY U-9100           NATURAL GAS GAS     34346
6   FI91507_PV  Sm3/h  UTILITY U-9100          POTABLE    WATER         0
7   FI91508_PV  TNE/H  UTILITY U-9100         HIGH PRESS  STEAM     34886
8   FI91509_PV  Sm3/h  UTILITY U-9100               DEMI WATER      33705
9   FI91510_PV  Sm3/h  UTILITY U-9100    BOILER      FEED WATER     34784
10  FI91512_PV  Sm3/h  UTILITY U-9100         PROCESS     WATER       823
11  FI91513_PV  Sm3/h  UTILITY U-9100         SERVICE     WATER      2182
12  FI10203_PV  Sm3/h   UTILITY U-100  COOLING     WATER SUPPLY     34902
13  FI20203_PV  Sm3/h   UTILITY U-200  COOLING     WATER SUPPLY     34893
14  FI25205_PV  Sm3/h   UTILITY U-250  COOLING     WATER SUPPLY     34879
15  FI40205_PV  Sm3/h   UTILITY U-400     CWS         FROM 9100     34885
16  FI50205_PV  Sm3/h   UTILITY U-500  COOLING     WATER SUPPLY     34872
17  FI60204_PV  Sm3/h   UTILITY U-600  COOLING     WATER SUPPLY     34879
18  FI65204_PV  Sm3/h   UTILITY U-650  COOLING     WATER SUPPLY     34902
19  FI70253_PV  Sm3/h   UTILITY U-700     CWS         FROM 9100     34902

In [62]:
display(HTML("<h3>Product Files</h3>"))
display(product_table)

            TAG   Unit     Equipment                      Desc.  #Value>0
0   FIC10014_PV   KG/H       TK-8105   C5          CUT PRODUCT      22846
1   FIC20017_PV   KG/H        E-2004   HEAVY       ENDS PRODUCT     34761
2   FIC20018_PV   KG/H        E-2003      HEART       CUT TO TK     34696
3   FIC25021_PV   KG/H        E-2505   HYDROTREATEDNAPHTHA TO T     34580
4   FIC30018_PV  Sm3/h        E-4001        REFORMATE TO E-4001     33669
5   FIC30018_PV  Sm3/h        E-4001        REFORMATE TO E-4001     33669
6   FIC40045_PV   KG/H        E-4006     ORTHOXYLENE TO STORAGE     34420
7   FIC50011_PV   KG/H       TK-8106       RAFFINATE TO TK-8106     34000
8   FIC60020_PV   KG/H  P-6007A/B         P-6007A/B   DISCHARGE     34901
9   FIC65004_PV   KG/H         E6502      HEAVY       AROMATICS     33616
10  FIC70053_PV   KG/H        E-7006      PARAXYLENE TO TK-7003     33402
11  FIC95008_PV   KG/H        E-9506  EWEET LTE TO TANK-8102C/D     34444